export type Ingredient = {id:string;name:string;amount?:number;max?:number;unit?:string;note?:string;fixed?:string};
export type IngredientGroup = {id:string;title:string;description:string;items:Ingredient[]};
export type TimerPreset = {id:string;label:string;minutes:number;message:string;next?:TimerPreset};
export type CookingStage = {id:string;phase:"Prep"|"Cook"|"Finish";title:string;time:string;equipment:string;instructions:string[];cue?:string;why?:string;parallel?:string;timer?:TimerPreset;tips?:{title:string;text:string}[]};
export type Nutrition={calories:number;protein:number;carbs:number;fat:number;fibre:number};
export type Recipe = {nutrition:{greek:Nutrition;soy:Nutrition};slug:string;title:string;image:string;defaultServings:number;groups:IngredientGroup[];equipment:string[];stages:(servings:number,frozen:boolean)=>CookingStage[]};
export function number(n:number){return Number(n.toFixed(1)).toString()}
export function quantity(item:Ingredient,servings:number){if(item.fixed)return item.fixed;const factor=servings/5;return `${number((item.amount??0)*factor)}${item.max?`–${number(item.max*factor)}`:""} ${item.unit??""}`.trim()}
const grams=(n:number,s:number)=>`${Math.round(n*s/5)} g`;
const scaled=(n:number,s:number,unit:string)=>`${number(n*s/5)} ${unit}`;
export const recipes:Recipe[]=[{
  nutrition:{greek:{calories:600,protein:48,carbs:80,fat:8,fibre:13},soy:{calories:585,protein:44,carbs:78,fat:9,fibre:13}},
  slug:"creamy-peri-peri-soy",title:"Creamy Peri-Peri Soy Chunk Meal Prep",image:"/images/peri-peri-soy.webp",defaultServings:5,
  equipment:["Large pot + colander","Saucepan with a snug lid","Large frying pan","2 baking trays","Mixing bowls + spatula","Kitchen scales","Shallow meal containers + sauce pots"],
  groups:[
    {id:"soy",title:"The soy chunks",description:"Dry weight first. Season generously after squeezing.",items:[
      {id:"soy-dry",name:"Dry soy chunks",amount:300,unit:"g"},{id:"soy-water",name:"Water for boiling",fixed:"Plenty",note:"Enough to cover the expanded chunks comfortably"},{id:"soy-salt",name:"Salt + black pepper",fixed:"To taste"},
      {id:"soy-paprika",name:"Smoked paprika",amount:2,unit:"tsp"},{id:"soy-cumin",name:"Ground cumin",amount:2,unit:"tsp"},{id:"soy-garlic",name:"Garlic powder",amount:1.5,unit:"tsp"},{id:"soy-onion",name:"Onion powder",amount:1,unit:"tsp"},{id:"soy-chilli",name:"Chilli powder or flakes",amount:1,unit:"tsp",note:"Start lower if your peri-peri sauce is hot"},{id:"soy-garam",name:"Garam masala",amount:1,unit:"tsp"},{id:"soy-lemon",name:"Lemon juice",amount:2,unit:"tbsp"},{id:"soy-peri",name:"Garlic peri-peri sauce",amount:40,max:50,unit:"g"},{id:"soy-oil",name:"Oil for pan-frying",amount:1,unit:"tbsp",note:"15 ml measuring spoon; divide between batches"}
    ]},
    {id:"rice",title:"Fluffy basmati rice",description:"White basmati, not brown rice. No soaking needed.",items:[{id:"rice-dry",name:"Dry basmati rice",amount:300,unit:"g"},{id:"rice-water",name:"Water for absorption cooking",amount:600,unit:"ml",note:"Use your packet’s ratio if it differs"},{id:"rice-salt",name:"Salt",fixed:"A small pinch"}]},
    {id:"broccoli",title:"Roasted broccoli",description:"Fresh or frozen. Give the florets plenty of room.",items:[{id:"broccoli",name:"Broccoli florets",amount:750,max:1000,unit:"g",note:"875 g used for the nutrition estimate"},{id:"broccoli-oil",name:"Oil",amount:2,unit:"tsp"},{id:"broccoli-garlic",name:"Garlic powder",amount:1,unit:"tsp"},{id:"broccoli-paprika",name:"Smoked paprika",amount:.5,unit:"tsp"},{id:"broccoli-salt",name:"Salt + pepper",fixed:"To taste"},{id:"broccoli-lemon",name:"Lemon juice to finish",amount:1,unit:"tbsp"}]},
    {id:"sauce",title:"Creamy peri-peri sauce",description:"Start mild, taste, then dial up the flavour.",items:[{id:"yogurt",name:"High-protein plain Greek yogurt",amount:400,unit:"g",note:"Or unsweetened soy yogurt for the vegan version"},{id:"sauce-peri",name:"Garlic peri-peri sauce",amount:80,max:100,unit:"g"},{id:"sauce-lemon",name:"Lemon juice",amount:1,unit:"tbsp"},{id:"sauce-garlic",name:"Garlic powder",amount:1,unit:"tsp"},{id:"sauce-paprika",name:"Smoked paprika",amount:.5,unit:"tsp"},{id:"sauce-cumin",name:"Ground cumin",amount:.5,unit:"tsp"},{id:"sauce-salt",name:"Salt",fixed:"A pinch"},{id:"sauce-water",name:"Water to loosen",amount:2,max:4,unit:"tbsp",note:"Add gradually; you may need less"},{id:"sauce-sweet",name:"Maple syrup or sugar",amount:.5,unit:"tsp",note:"Optional, only if the sauce tastes too sharp"}]}
  ],
  stages:(s,frozen)=>[
    {id:"setup",phase:"Prep",title:"Get the heat going",time:"3 min",equipment:"Oven + large pot",instructions:["Wash your hands and clear a working space. Set out your pots, bowls and trays.","Preheat the oven to 220°C fan / 240°C conventional.","Fill a large pot with plenty of water, add a little salt and bring to a rolling boil. Leave room for the soy chunks to expand."],parallel:"While the pot heats, rinse the rice. For larger batches, use extra trays and allow more frying time."},
    {id:"rinse",phase:"Prep",title:"Measure and rinse the rice",time:"3–4 min",equipment:"Bowl + fine sieve",instructions:[`Measure ${grams(300,s)} dry white basmati rice into a bowl.`,"Cover with cold water, gently swish the grains with your fingers, then pour off the cloudy water. Repeat 3–5 times until the water is considerably clearer.","Drain well in a fine sieve. Set beside the saucepan; don’t add it to the soy pot."],cue:"The rinse water is translucent rather than milky. It does not have to be perfectly clear.",why:"Rinsing removes loose surface starch, helping the grains stay separate."},
    {id:"rehydrate",phase:"Cook",title:"Rehydrate the soy chunks",time:"5–10 min",equipment:"Large pot",instructions:[`Add ${grams(300,s)} dry soy chunks to the boiling water. Stir once so all the chunks get wet.`,"Reduce to a steady simmer. Follow the packet timing, usually 5–10 minutes. Stir occasionally; add more hot water if the chunks aren’t submerged.","Cut one chunk open to check. Extend the simmer if the centre is still hard or dry."],cue:"Fully swollen and soft all the way through, with no dry, firm centre.",parallel:"While they simmer, start the rinsed rice in its own saucepan.",timer:{id:"soy-simmer",label:"Soy simmer",minutes:8,message:"Check a soy chunk’s centre. Drain only when fully softened; your packet timing takes priority."}},
    {id:"rice-start",phase:"Cook",title:"Start the rice, then leave it alone",time:"12 min + 10 min rest",equipment:"Saucepan + snug lid",instructions:[`Put the drained rice in a saucepan with ${scaled(600,s,"ml")} cold water and a small pinch of salt. This starting ratio is 200 ml water per 100 g dry rice; follow your packet if it specifies a different ratio.`,"Bring to a gentle boil, uncovered, over medium-high heat. You should see bubbles across the surface.","Immediately turn to the lowest heat and cover with a snug lid. Simmer for about 12 minutes. Start the rice timer now; do not stir or keep lifting the lid.","When the timer finishes, turn the heat OFF. Move off a hot electric hob. Keep covered for 10 more minutes before fluffing."],cue:"A quiet simmer, not an aggressive boil. A small batch needs a small saucepan so water doesn’t evaporate too fast.",parallel:"Let the rice cook while you squeeze the soy and prepare the broccoli.",timer:{id:"rice-simmer",label:"Rice simmer",minutes:12,message:"Turn the rice heat OFF now. Move off a hot hob and keep the lid on. Start the 10-minute rest.",next:{id:"rice-rest",label:"Rice rest",minutes:10,message:"The rice has rested. Gently fluff it with a fork. If other food is still cooking, spread rice in a shallow container and refrigerate promptly."}}},
    {id:"squeeze",phase:"Prep",title:"Drain. Cool. Squeeze really well",time:"5–8 min",equipment:"Colander + clean hands",instructions:["When the soy chunks have no dry centres, drain them in a colander. Let them cool until comfortable to touch. A quick cool-water rinse helps if they are too hot.","Take a small handful at a time and squeeze firmly over the sink. Repeat until very little water comes out. Don’t burn your hands.","Put the squeezed chunks into a large mixing bowl."],cue:"Damp and springy, but no longer dripping. They should feel much less waterlogged.",why:"Soy chunks are sponges. Excess water dilutes seasoning and makes the pan steam instead of brown. Squeezing is the most important texture step."},
    {id:"broccoli",phase:"Cook",title:"Get the broccoli roasting",time:frozen?"25–30 min":"20–25 min",equipment:"Oven + baking trays",instructions:[frozen?`Use ${grams(750,s)}–${grams(1000,s)} frozen florets straight from the freezer. Do not thaw. Break apart any clumps.`:`Wash ${grams(750,s)}–${grams(1000,s)} broccoli. Cut into bite-sized florets; peel and slice tender stalks. Dry thoroughly with a clean towel.`,`Toss with ${scaled(2,s,"tsp")} oil, ${scaled(1,s,"tsp")} garlic powder, ${scaled(.5,s,"tsp")} smoked paprika, salt and pepper.`,"Spread in one layer across trays, with gaps between florets. Crowded broccoli steams; use two trays for the default batch.",`Roast at 220°C fan / 240°C conventional for ${frozen?"25–30":"20–25"} minutes. Turn the florets and swap tray positions halfway. Start the timer after the trays go in.`],cue:"Bright-to-deep green with browned tips. A fork slides into the stalk with a little resistance; the florets still hold their shape.",parallel:"While the oven works, season the soy and mix the cold sauce.",timer:{id:"broccoli-half",label:"Turn broccoli",minutes:frozen?13:11,message:"Turn the broccoli and swap the trays’ positions. Continue roasting until tender with browned tips.",next:{id:"broccoli-finish",label:"Finish broccoli",minutes:frozen?14:11,message:"Check the broccoli: browned tips, tender stalks, no mush. Add a few minutes only if needed."}}},
    {id:"season",phase:"Prep",title:"Coat the soy in flavour",time:"3 min · optional 10–20 min sit",equipment:"Large mixing bowl",instructions:[`To the squeezed soy, add ${scaled(2,s,"tsp")} smoked paprika, ${scaled(2,s,"tsp")} cumin, ${scaled(1.5,s,"tsp")} garlic powder, ${scaled(1,s,"tsp")} onion powder, ${scaled(1,s,"tsp")} garam masala and up to ${scaled(1,s,"tsp")} chilli.`,`Add ${scaled(2,s,"tbsp")} lemon juice and ${grams(40,s)}–${grams(50,s)} garlic peri-peri sauce. Season with salt and black pepper, remembering the bottled sauce may already be salty.`,"Mix thoroughly until every chunk is coated. Let sit 10–20 minutes if time allows; making the sauce gives it a useful head start."],cue:"An even red-orange coating, with no pool of watery liquid in the bowl.",why:"The spice amounts are a starting point, not a strict formula. Use less chilli first; you can add heat later."},
    {id:"sauce",phase:"Prep",title:"Make the creamy peri-peri sauce",time:"5 min",equipment:"Bowl + spoon",instructions:[`Add ${grams(400,s)} yogurt to a bowl and stir until smooth. Start with ${grams(80,s)} garlic peri-peri sauce.`,`Mix in ${scaled(1,s,"tbsp")} lemon juice, ${scaled(1,s,"tsp")} garlic powder, ${scaled(.5,s,"tsp")} smoked paprika, ${scaled(.5,s,"tsp")} cumin and a pinch of salt.`,`Add water a little at a time, up to about ${scaled(2,s,"tbsp")}–${scaled(4,s,"tbsp")}. Mix after each addition.`,"Taste, adjust using the notes below, then cover and refrigerate until serving or portioning."],cue:"Smooth, thick but pourable. It should fall from a spoon in a slow ribbon, not run like water.",tips:[{title:"More kick?",text:`Add peri-peri gradually, up to around ${grams(100,s)} total or to taste.`},{title:"Too flat?",text:"Add a little salt. A small squeeze of lemon makes the flavour brighter."},{title:"Too sharp?",text:`Try a tiny amount of sweetness, up to about ${scaled(.5,s,"tsp")} maple syrup or sugar.`},{title:"Too hot or thin?",text:"Extra yogurt softens the heat and thickens the sauce. This changes the nutrition slightly."}],parallel:"Check the rice and broccoli timers before you start pan-frying."},
    {id:"fry",phase:"Cook",title:"Brown the soy, don’t steam it",time:"12–20 min for the batch",equipment:"Large frying pan",instructions:["Heat a large frying pan over medium-high heat for 1–2 minutes. Add a little of the measured oil; it should shimmer without smoking.",`Use about ${scaled(1,s,"tbsp")} oil across all batches. Add only enough soy for a single uncrowded layer, usually 2–3 batches for five meals.`,"Let the chunks sit against the hot pan for about 2 minutes before turning. Then cook for roughly 5–7 minutes per batch, turning occasionally, until hot throughout with browned edges.","If the sauce starts burning, lower the heat a little. Taste a cooked piece and adjust salt, lemon, spices or peri-peri. Transfer to a clean bowl and repeat."],cue:"Browned or lightly charred edges, a flavourful exterior and a chewy bite. No wet, sponge-like texture or puddle in the pan.",tips:[{title:"Soggy?",text:"Cook longer to evaporate moisture. Next time, squeeze more thoroughly before seasoning."},{title:"Not browning?",text:"Use fewer chunks per batch and let the pan heat up. Give them contact time before stirring."},{title:"Bland?",text:"Taste a cooked chunk, then add a little salt, lemon or peri-peri. More chilli alone does not fix blandness."}],parallel:"Attend to the rice or broccoli as soon as their timer calls for it. Frying time grows with the number of batches.",timer:{id:"soy-contact",label:"First browning",minutes:2,message:"Turn a few soy chunks. Look for brown edges; continue frying until hot and chewy."}},
    {id:"finish-rice",phase:"Finish",title:"Fluff the rested rice",time:"1–2 min",equipment:"Fork",instructions:["Check that the rice heat is off and it has rested, covered, for 10 minutes.","Lift the lid and gently separate the grains with a fork. Don’t mash or stir vigorously.","If you are still cooking the other components, spread the rice in shallow containers and refrigerate promptly rather than leaving it in the warm pot."],cue:"Tender, separate grains with no standing water.",tips:[{title:"Still firm and dry?",text:"Sprinkle in a little boiling water, cover and cook on low for 2–3 minutes, then rest for 5 minutes."},{title:"Water still visible?",text:"Cook on low, covered, for 2–3 more minutes, then rest. Use a little less water next time if your packet recommends it."}]},
    {id:"finish-broccoli",phase:"Finish",title:"Give the broccoli a final check",time:"1 min",equipment:"Fork + trays",instructions:["Check a thick stalk with a fork. Remove trays once the stalks are tender with a slight bite and the tips have some colour.",`Finish with about ${scaled(1,s,"tbsp")} lemon juice. Taste and adjust salt or pepper.`,"If still firm, roast a few minutes more. If the tips darken too fast, reduce the oven by 20°C."],cue:"Bite-sized, seasoned and tender. Not limp, grey or collapsing."},
    {id:"assembly",phase:"Finish",title:`Build your ${s} meal${s===1?"":"s"}`,time:"5 min",equipment:`${s} shallow container${s===1?"":"s"} + sauce pots`,instructions:[`Lay out ${s} shallow meal container${s===1?"":"s"}. Divide the rice, soy and broccoli evenly. Give each a little of each component in rounds, then balance the leftovers.`,"For precision, weigh the full cooked amount of each component separately and divide that weight by your number of containers. Water absorption makes cooked weights vary.","Each meal represents 60 g dry rice, 60 g dry soy and around 150–200 g raw broccoli. Expect roughly 150–180 g cooked rice and 120–180 g squeezed cooked soy, but use equal shares rather than chasing these ranges.",`Divide the sauce into ${s} separate small pots, approximately 100–115 g each including sauce and water. Keep it cold; add it after reheating.`],cue:"Equal portions of all three warm components, with the creamy sauce kept separately.",why:"Separate sauce stays creamy and lets you heat the rice and soy thoroughly without splitting the yogurt."},
    {id:"chill",phase:"Finish",title:"Cool quickly and put tomorrow’s lunch away",time:"Promptly · don’t wait hours",equipment:"Fridge + freezer",instructions:["Spread food in shallow portions; let heavy steam escape briefly, then refrigerate promptly. Don’t wait for a whole pot to cool on the bench. Aim to chill rice within 1 hour; always get food into the fridge within 2 hours.","Keep the fridge below 5°C. Leave space around cooling containers; loosely cover while cooling, then seal once cold.","Keep only portions you will eat within 2 days in the fridge. Freeze later portions the same day after cooling quickly; label with the date. Freeze the warm components without sauce.","Keep sauce separately in the fridge and use within 3 days, or sooner if the yogurt’s use-by date or opening instructions require it. Make a fresh small batch for later frozen meals."],cue:"Shallow, dated containers in the fridge or freezer, not a five-day batch sitting on the bench.",why:"Rice can harbour spores and heat-stable toxins if kept warm too long. Reheating cannot rescue rice that was stored badly."}
  ]
}];
export const recipe=recipes[0];
export const nutrition={greek:{calories:600,protein:48,carbs:80,fat:8,fibre:13},soy:{calories:585,protein:44,carbs:78,fat:9,fibre:13}};
